---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paid-dapp-nextjs
  labels:
    app: dapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dapp
    spec:
      containers:
        - image: gcr.io/vivid-plateau-278712/paid-dapp-nextjs:cicd-development-latest
          imagePullPolicy: Always
          name: dapp
          ports:
            - containerPort: 3000
