---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paid-dapp
  labels:
    app: dapp-nextjs
  namespace: paid-nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapp-nextjs
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dapp-nextjs
    spec:
      containers:
        - image: gcr.io/vivid-plateau-278712/paid-dapp:paid-main-nextjs-app-latest
          name: dapp
          ports:
            - containerPort: 3000
