---
apiVersion: v1
kind: Service
metadata:
  name: paid-dapp-nextjs
  labels:
    app: dapp-nextjs
  namespace: paid-nextjs
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: dapp-nextjs
  type: LoadBalancer