apiVersion: v1
kind: Service
metadata:
  name: paid-dapp
  labels:
    app: dapp-binance
  namespace: paid-binance
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: dapp-binance
  type: LoadBalancer