---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paid-dapp
  labels:
    app: dapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dapp
    spec:
      containers:
        - image: gcr.io/vivid-plateau-278712/paid-dapp:develop-latest
          name: dapp
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paid-dapp
  labels:
    app: dapp-binance
  namespace: paid-binance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapp-binance
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dapp-binance
    spec:
      containers:
        - image: gcr.io/vivid-plateau-278712/paid-dapp:binanceSC-paid-dapp-latest
          name: dapp
          ports:
            - containerPort: 80
